// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEH0tDj5Uj2fjMdSqkeCu55DImiMBL3PA',
    appId: '1:933078954963:web:44422280d1fae5d3b1b526',
    messagingSenderId: '933078954963',
    projectId: 'instagramclone-8b51a',
    authDomain: 'instagramclone-8b51a.firebaseapp.com',
    storageBucket: 'instagramclone-8b51a.appspot.com',
    measurementId: 'G-71D73VBCDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyBlPpi56Y7lJS6Bit7QJJjQ6oXi9ugI',
    appId: '1:933078954963:android:01efd207eba9314bb1b526',
    messagingSenderId: '933078954963',
    projectId: 'instagramclone-8b51a',
    storageBucket: 'instagramclone-8b51a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9zMfHnyEcQSw8iH2inF6DVNDpLHdye18',
    appId: '1:933078954963:ios:e6ce8d59dcce1616b1b526',
    messagingSenderId: '933078954963',
    projectId: 'instagramclone-8b51a',
    storageBucket: 'instagramclone-8b51a.appspot.com',
    iosClientId: '933078954963-vm38hhjp5ifphee539dpf2s69gviu1uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9zMfHnyEcQSw8iH2inF6DVNDpLHdye18',
    appId: '1:933078954963:ios:e6ce8d59dcce1616b1b526',
    messagingSenderId: '933078954963',
    projectId: 'instagramclone-8b51a',
    storageBucket: 'instagramclone-8b51a.appspot.com',
    iosClientId: '933078954963-vm38hhjp5ifphee539dpf2s69gviu1uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
